apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "Pruebas backstage JC"
  description: "Primera con JC"
  annotations:
    github.com/project-slug: Backstage-org/repo-prueba-nuevo
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: "Backstage-org"
